// INCLUDING A, B, C, D, E
const columnB = [
  "Anchovy apple",
  "Asparagus ice cream",
  "Eggplant yogurt",
  "Avocado smoothie",
  "Eel Jell-O",
  "Aged custard",
  "Apple casserole",
  "Artichoke salad",
  "Edamame cake",
  "Apricot pie",
  "Brussels cake",
  "Alfalfa sandwich",
  "Eggplant fudge",
  "Anchovy stew",
  "Apple relish",
  "Acorn pudding",
  "Edible clay",
  "Espresso soup",
  "Acorn soup",
  "Almond jelly",
];

// INCLUDING F, G, H, I, J
const columnI = [
  "Fennel sorbet",
  "Fish smoothie",
  "Fermented beans",
  "Fried tarantula",
  "Faux granola",
  "Fig tart",
  "Fry water",
  "Frozen liver",
  "Grape soup",
  "Jelly jam",
  "Jalapeño cotton",
  "Jicama sandwich",
  "Fudge combo",
  "Fig pancake",
  "Jalapeño donut",
  "Fried yogurt",
  "Fruit mayo",
  "Jerk cheese",
  "Fig parfait",
  "Hot licorice",
  "Ham tart",
  "Herring chocolate",
  "Honey sushi",
  "Hamburger popsicle",
  "Horseradish ice",
  "Hot yogurt",
  "Honey pickle",
];

// INCLUDING K, L, M, N, 0
const columnN = [
  "Lemon mousse",
  "Lobster Jell-O",
  "Lychee salad",
  "Leek gummy",
  "Melon tart",
  "Leek cookies",
  "Marzipan salad",
  "Mustard soup",
  "Mac olives",
  "Mango jelly",
  "Mummy salad",
  "Mince pie",
  "Melon casserole",
  "Mackerel pops",
  "Mustard ice",
  "Molasses cake",
  "Mushroom jelly",
];

// INCLUDING P, Q, R, S, T
const columnG = [
  "Pudding mushrooms",
  "Roquefort sandwich",
  "Raisin meatloaf",
  "Radish fudge",
  "Roast chicken",
  "Rye soup",
  "Rice smoothie",
  "Root beer chicken",
  "Sardine cupcakes",
  "Spaghetti smoothie",
  "Sauerkraut ice",
  "Sweet jelly",
  "Shrimp applesauce",
  "Spinach salad",
  "Sausage pudding",
  "Squid lemonade",
  "S'mores anchovy",
  "Salted cucumber",
  "Strawberry parfait",
  "Stewed cookies",
  "Smoked pizza",
  "Sweet lime",
  "Squash soup",
  "Squash soda",
  "Tarragon ice cream",
];

// INCLUDING U, V, W, X, Y, Z
const columnO = [
  "Zucchini donut",
  "Udon pancakes",
  "Vinegar ice cream",
  "Vegetable cake",
  "Worm syrup",
  "Whipped tuna",
  "Watermelon spaghetti",
  "Waffles with mustard",
  "Yam jelly",
  "Yogurt pasta",
  "Zoloft cake",
  "Xanax soup",
  "Xmas fruit salad",
  "Yellow squash tart",
  "Yogurt fries",
  "Zebra cake",
  "Zesty pickles",
  "Zucchini muffins",
  "Vegan cheese ice cream",
  "Vinegar popsicles",
  "Worm salad",
  "Wild berry stew",
  "White chocolate pickles",
];
